"""Random inputs for word-pattern-match.

Built so that both answers occur often: a matching pair is generated by choosing
a shape and a distinct word per letter, and a failing pair by breaking exactly
one of the two directions - a letter given a second word, or a word given a
second letter.
"""

import random
import string
from typing import Any, Dict, Iterator, List

WORDS = ["rain", "snow", "hail", "mist", "wind", "dust", "fog", "sun", "ice", "dew"]


def _case(shape: str, sentence: str, name: str = None) -> Dict[str, Any]:
    case: Dict[str, Any] = {"args": [shape, sentence]}
    if name:
        case["name"] = name
    return case


def _matching(rng: random.Random, letters: int, length: int) -> Dict[str, Any]:
    alphabet = string.ascii_lowercase[:letters]
    words = rng.sample(WORDS, letters)
    shape = "".join(rng.choice(alphabet) for _ in range(length))
    sentence = " ".join(words[alphabet.index(letter)] for letter in shape)
    return _case(shape, sentence)


def generate(rng: random.Random) -> Iterator[Dict[str, Any]]:
    yield _case("a", "rain", "one letter, one word")
    yield _case("a", "rain snow", "one letter against two words")
    yield _case("ab", "rain rain", "two letters sharing a word")
    yield _case("aa", "rain rain", "one letter used twice, correctly")
    yield _case("aa", "rain snow", "one letter needing two words")
    yield _case("abcabc", "rain snow hail rain snow hail", "three letters, twice over")

    for letters, length in ((2, 4), (3, 9), (5, 20), (4, 60)):
        yield _matching(rng, letters, length)

        # Break the letter -> word direction at one position.
        broken = _matching(rng, letters, length)
        words = broken["args"][1].split(" ")
        spare = next(w for w in WORDS if w not in words)
        words[rng.randrange(len(words))] = spare
        yield _case(broken["args"][0], " ".join(words))

    # Break the word -> letter direction: every word the same, shape varied.
    yield _case("abcd", "mist mist mist mist", "four letters claiming one word")

    # The stated maxima: 300 letters, and nine-letter words so that the sentence
    # reaches 2999 characters rather than stopping well short of the bound.
    letters = 10
    alphabet = string.ascii_lowercase[:letters]
    words = ["northerly", "southerly", "easterlyx", "westerlyx", "overcasts",
             "drizzling", "blustered", "sweltered", "hailstone", "snowdrift"]
    shape = "".join(rng.choice(alphabet) for _ in range(300))
    sentence = " ".join(words[alphabet.index(letter)] for letter in shape)
    yield _case(shape, sentence, "the stated maximum shape and sentence length")
